compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
main_process_port: 29503
downcast_bf16: 'no'
enable_cpu_affinity: false
gpu_ids: 0,1,2,3,4,5,6,7
# gpu_ids: 0,
machine_rank: 0
main_training_function: main
mixed_precision: bf16
# num_machines: 1
num_processes: 8
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false